table GeographicInformation
	lineageTag: e244d13b-6eb8-4c4d-8241-ce37802fcec8

	column 'Site code'
		dataType: string
		lineageTag: f5942e89-47e1-4c1a-9a07-42b4b89b3716
		summarizeBy: none
		sourceColumn: Site code

		annotation SummarizationSetBy = Automatic

	column 'Site name'
		dataType: string
		lineageTag: f5b3339b-b3ab-49d1-95bb-2a224472f1ab
		summarizeBy: none
		sourceColumn: Site name

		annotation SummarizationSetBy = Automatic

	column Address
		dataType: string
		lineageTag: 9e09b7a2-a1ee-4fea-983f-5f1d8aea00fc
		summarizeBy: none
		sourceColumn: Address

		annotation SummarizationSetBy = Automatic

	column District
		dataType: string
		lineageTag: 24abe3d4-4f40-40e1-9e9d-ba06cd72affc
		summarizeBy: none
		sourceColumn: District

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: double
		lineageTag: 10c10616-2707-48b1-b2a0-a51e8f9d5e84
		summarizeBy: sum
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Longitude
		dataType: double
		lineageTag: d66a2ec0-3dd1-4711-9252-b27998911da2
		summarizeBy: sum
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition GeographicInformation = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Celine Wang\OneDrive - Rosino-Axle\Desktop\Celine Wang\Project Caspian\Replicate\PowerBI Illustration\Esso_Site_Info.xlsx"), null, true),
				    GeographicInformation_Table = Source{[Item="GeographicInformation",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(GeographicInformation_Table,{{"Site code", type text}, {"Site name", type text}, {"Address", type text}, {"District", type text}, {"Latitude", type number}, {"Longitude", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

