table GrossSales
	lineageTag: e27e8c08-6dc0-4382-bca7-2ac60b30a5fc

	column 'Site name'
		dataType: string
		lineageTag: e0adec0c-4886-416d-a7de-0de1d896970e
		summarizeBy: none
		sourceColumn: Site name

		annotation SummarizationSetBy = Automatic

	column MonthText
		dataType: string
		lineageTag: 8b2e71c9-1f3d-433a-8dd5-58c18a588c29
		summarizeBy: none
		sourceColumn: MonthText

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: acbf2c0a-7a9a-4ca6-81f1-09e130c1cc57
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MonthStart
		dataType: dateTime
		formatString: Long Date
		lineageTag: 88ff5d90-5cee-430b-9335-81cfcb4453a6
		summarizeBy: none
		sourceColumn: MonthStart

		variation Variation
			isDefault
			relationship: d78dd693-7004-41ed-adb4-e83f39e57640
			defaultHierarchy: LocalDateTable_d980a04f-ea2c-4511-b618-519a476f07dc.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MonthLabel
		dataType: string
		lineageTag: 4f52734b-2960-45dd-817c-819b7f942566
		summarizeBy: none
		sourceColumn: MonthLabel

		annotation SummarizationSetBy = Automatic

	column SiteKey
		dataType: string
		lineageTag: c03c6465-dcbb-49d4-a5ea-26e4cbf34309
		summarizeBy: none
		sourceColumn: SiteKey

		annotation SummarizationSetBy = Automatic

	column Metric
		dataType: string
		lineageTag: bdd251c0-df1d-489f-8174-d02ea9b647a0
		summarizeBy: none
		sourceColumn: Metric

		annotation SummarizationSetBy = Automatic

	partition GrossSales = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Celine Wang\OneDrive - Rosino-Axle\Desktop\Celine Wang\Project Caspian\Replicate\PowerBI Illustration\Esso_Site_Info.xlsx"), null, true),
				    GrossSales_Table = Source{[Item="GrossSales",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(GrossSales_Table,{{"Site name", type text}, {"FY22", type number}, {"FY23", type number}, {"FY24", type number}, {"TTM25", type number}, {"6m24", type number}, {"6m25", type number}, {"Jan22", type number}, {"Feb22", type number}, {"Mar22", type number}, {"Apr22", type number}, {"May22", type number}, {"Jun22", type number}, {"Jul22", type number}, {"Aug22", type number}, {"Sep22", type number}, {"Oct22", type number}, {"Nov22", type number}, {"Dec22", type number}, {"Jan23", type number}, {"Feb23", type number}, {"Mar23", type number}, {"Apr23", type number}, {"May23", type number}, {"Jun23", type number}, {"Jul23", type number}, {"Aug23", type number}, {"Sep23", type number}, {"Oct23", type number}, {"Nov23", type number}, {"Dec23", type number}, {"Jan24", type number}, {"Feb24", type number}, {"Mar24", type number}, {"Apr24", type number}, {"May24", type number}, {"Jun24", type number}, {"Jul24", type number}, {"Aug24", type number}, {"Sep24", type number}, {"Oct24", type number}, {"Nov24", type number}, {"Dec24", type number}, {"Jan25", type number}, {"Feb25", type number}, {"Mar25", type number}, {"Apr25", type number}, {"May25", type number}, {"Jun25", type number}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"FY22", "FY23", "FY24", "TTM25", "6m24", "6m25"}),
				    #"Unpivoted Only Selected Columns" = Table.Unpivot(#"Removed Columns", {"Jan22", "Feb22", "Mar22", "Apr22", "May22", "Jun22", "Jul22", "Aug22", "Sep22", "Oct22", "Nov22", "Dec22", "Jan23", "Feb23", "Mar23", "Apr23", "May23", "Jun23", "Jul23", "Aug23", "Sep23", "Oct23", "Nov23", "Dec23", "Jan24", "Feb24", "Mar24", "Apr24", "May24", "Jun24", "Jul24", "Aug24", "Sep24", "Oct24", "Nov24", "Dec24", "Jan25", "Feb25", "Mar25", "Apr25", "May25", "Jun25"}, "Attribute", "Value"),
				    #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Only Selected Columns",{{"Attribute", "MonthText"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "MonthStart", each let
				    t = Text.Remove([MonthText], {" ", "-","/"}),
				    mmm = Text.Proper(Text.Start(t, 3)),
				    yy  = Text.End(t, 2),
				    year = 2000 + Number.FromText(yy),
				    monthMap = [
				        Jan=1, Feb=2, Mar=3, Apr=4, May=5, Jun=6,
				        Jul=7, Aug=8, Sep=9, Oct=10, Nov=11, Dec=12
				    ],
				    monthNum = Record.Field(monthMap, mmm)
				in
				    #date(year, monthNum, 1)),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"MonthStart", type date}}),
				    #"Added Custom1" = Table.AddColumn(#"Changed Type1", "MonthLabel", each Date.ToText([MonthStart], "yyyy-MM")),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Metric", each "GrossSales"),
				    #"Merged Queries" = Table.NestedJoin(#"Added Custom2", {"Site name"}, Overview_Code, {"Site name"}, "Overview_Code", JoinKind.LeftOuter),
				    #"Expanded Overview_Code" = Table.ExpandTableColumn(#"Merged Queries", "Overview_Code", {"SiteKey"}, {"SiteKey"})
				in
				    #"Expanded Overview_Code"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

