table SiteCounts
	lineageTag: fca2999b-ddcc-4c37-a7a0-947508c223db

	measure 'Site Count' =
			
			DISTINCTCOUNT(DimSite[SiteKey])
		formatString: 0
		lineageTag: a664d28c-ba87-4ba8-833c-93d4499f2788

	measure 'Sites with Sales (Selected Period)' =
			
			COUNTROWS(
			    FILTER(VALUES(DimSite[SiteKey]), NOT ISBLANK([Net Sales (Selected Period)]))
			)
		formatString: 0
		lineageTag: 8e8fd28d-1217-4ee4-a865-8b0ed5a5d23f

	measure '# Sites District' =
			
			DISTINCTCOUNT(DimSite[SiteKey])
		formatString: 0
		lineageTag: cdfc5431-d9f3-4cdd-8f28-bc2e3a1df1c9

	measure 'Sites more than 3 districts' =
			
			VAR Threshold = 3
			VAR Dist = SELECTEDVALUE(DistrictAxisPlus[District])
			VAR ThisCnt = [# Sites District]   -- your DISTINCTCOUNT(DimSite[SiteKey]) measure
			RETURN
			IF(
			    Dist = "Others",
			    VAR OtherCnt =
			        SUMX(
			            FILTER(
			                ALL(DistrictAxisPlus[District]),
			                DistrictAxisPlus[District] <> "Others"
			            ),
			            VAR d = DistrictAxisPlus[District]
			            VAR c =
			                CALCULATE(
			                    [# Sites District],
			                    REMOVEFILTERS(DistrictAxisPlus),
			                    DistrictAxisPlus[District] = d
			                )
			            RETURN IF(c < Threshold, c, 0)
			        )
			    RETURN IF(OtherCnt > 0, OtherCnt, BLANK()),
			    IF(ThisCnt >= Threshold, ThisCnt, BLANK())
			)
		formatString: 0
		lineageTag: f192e8af-89aa-418c-b1b2-8de50116bbbf

	partition SiteCounts = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

